exports("GetNexusPlayer", GetNexusPlayer)
exports("GetNexusPlayerByCitizenId", GetNexusPlayerByCitizenId)
exports("SyncPlayerData", SyncPlayerData)
exports("GetNexusPlayers", function())
    return NexusPlayers
end)
exports("DatabaseFetchAll", function(query, parameters)
    return NexusDatabase.FetchAll(query, parameters)
end)
exports("DatabaseFetchSingle", function(query, parameters)
    return NexusDatabase.FetchSingle(query, parameters)
end)
exports("DatabaseExecute", function(query, parameters)
    return NexusDatabase.Execute(query, parameters)
end)
exports("DatabaseInsert", function(query, parameters)
    return NexusDatabase.Insert(query, parameters)
end)
exports("DatabaseOnReady", function(callback)
    return NexusDatabase.OnReady(callback)
end)
